### PR TITLE
Add data types for C#

### PR DESCRIPTION
**Pull request by siddhpant**
Added data types for C#. Indented the keywords.

Four data types (float, double, int, short) match exactly the C data types I defined in #44, so four files in this PR are exactly the same as in #44.

### CODE REVIEW

**Comment by jayvdb** [comment]
Comment on 004ba03d5638df14d0cade2dacbb582103fed507, file data/DataType/byte_cs.yaml, line 4.

trailing spaces (trailing-spaces)

*Origin: YAMLLintBear, Section: `yaml`.*

**Comment by siddhpant** [comment]
I just removed the trailing space...

**Comment by jayvdb** [comment]
I'll fix it up.

**Comment by siddhpant** [comment]
Updated data types in lieu of #48

I earlier had already added the precision attribute, but now I have declared it as an integer and not a string.

**Comment by jayvdb** [comment]
Comment on 004ba03d5638df14d0cade2dacbb582103fed507, file data/DataType/byte_cs.yaml, line 4.

trailing spaces (trailing-spaces)

*Origin: YAMLLintBear, Section: `yaml`.*

**Comment by siddhpant** [comment]
Rebased.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coAST/pull/46/commits/6221396666ffa602736730fda1fa70bca28d4fb7 https://github.com/coala/coAST/pull/46/commits/67413744becd2ccf0ce0d544a9b7cdb7bba68172

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
