### PR TITLE
README.md: Fix docstring typo

### PR DESCRIPTION
**Pull request by asrdav**
release--> released.

Closes https://github.com/coala/coAST/issues/76

### CODE REVIEW

**Comment by siddhpant** [comment]
Duplicate PR, please close.

**Comment by siddhpant** [comment]
Why did you spam the same PR again and again?

**Comment by asrdav** [comment]
Sorry, this was my first PR. I didn't know better

**Comment by shashank-b** [comment]
Hey @asrdav
At coala, creating duplicate PRs, closing PRs on your own and multiple commits for a single change is usually not done. I understand that this is your first issue so I'd suggest that you go through the Newcomer's Guide.

**Pull request closed without merging**
