### PR TITLE
Remove comment inconsistencies

### PR DESCRIPTION
**Pull request by tanmaysachan**
Fixes https://github.com/coala/coAST/issues/68

### CODE REVIEW

**Review by li-boxuan — CHANGES_REQUESTED** [review]
Use `Closes` instead of `Fixes` in your commit messages.
Your commit message is not in the correct format (hint: one space line is missing)

You have 10 commits which are doing the same thing and changes are small. Use one commit instead.

**Comment by tanmaysachan** [comment]
@li-boxuan updated commits.

**Review by Man-Jain — CHANGES_REQUESTED** [review]
There are 2 other files which have these inconsistencies like 
https://github.com/coala/coAST/blob/master/data/Language/x86.yaml
https://github.com/coala/coAST/blob/master/data/Language/JSON.yaml
Please fix these too

Also the commit head could be 
`Language: Fix comment inconsistencies`

It would also be nice if you add a little description for the commit.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by jayvdb** [comment]
ack https://github.com/coala/coAST/pull/80/commits/78e658e9f5bd2b500acc99db3d410e431750f25a

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
