### PR TITLE
Update Rust language definition

### PR DESCRIPTION
**Pull request by cubetastic33**
Update the rust language definition to include the creation date and the grammar file.

### CODE REVIEW

**Comment by Naveenaidu** [comment]
This PR is diverted from https://github.com/coala/coAST/pull/72.

**Comment by jayvdb** [comment]
@cubetastic33 , in future please do not close PRs and create a new one.  Work with the mentors to fix your existing one.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coAST/pull/74/commits/345bf23b0c0d5937832562be4a95a35496f78dee

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by jayvdb** [comment]
@cubetastic33 no worries.  A mentor explained what happened.

**Pull request merged**
